version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/myapp
    volumes:
      # Mount source code for development (hot reload)
      - ./server:/app/server
      # Mount plonky wasm verifier
      # TODO: move this to github?
      - ../plonky2-rsa-wasm-verify/pkg:/plonky2-rsa-wasm-verify/pkg
    # Command is defined in Dockerfile.dev
  client:
    image: node:23.11
    working_dir: /app/client
    ports:
      - '3000:3000'
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - ../plonky2-rsa-wasm-verify/pkg-web:/plonky2-rsa-wasm-verify/pkg-web
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:5000
    command: >
      sh -c "npm install && 
             npm run dev -- --host 0.0.0.0"

  mongodb:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=myapp
    # Healthcheck to ensure MongoDB is ready
    healthcheck:
      test: mongosh --eval 'db.adminCommand("ping")'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongodb_data:
    driver: local
