FROM node:23.11

# Set working directory
WORKDIR /app

# Install global development dependencies
RUN npm install -g nodemon

# Install root dependencies
COPY package*.json ./
RUN npm install

# Copy source code (rest will be mounted as volumes)
COPY server ./server

# Environment variables
ENV NODE_ENV=development
ENV PORT=5000

# Expose port
EXPOSE 5000

# Default command
CMD ["npm", "run", "server"]
